"""create users table

Revision ID: 8c926d63ec13
Revises: 
Create Date: 2024-12-15 23:27:47.932908

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c926d63ec13"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("father_name", sa.String(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("birth_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("service_id", name=op.f("uq_users_service_id")),
    )
    op.drop_table("Equipment")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Equipment",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("pos", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("label", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "inventory_index", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="Equipment_pkey"),
    )
    op.drop_table("users")
    # ### end Alembic commands ###
